# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ShortUrlRn.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ShortUrlRn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ShortUrlRn.proto\x12\nshorturlrn\x1a\x1fgoogle/protobuf/timestamp.proto\" \n\x0cUserRequests\x12\x10\n\x08username\x18\x01 \x01(\t\":\n\x14UserUrlListResponses\x12\"\n\x04urls\x18\x01 \x03(\x0b\x32\x14.shorturlrn.ShortURL\":\n\x11\x43reateUrlRequests\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\"\xa0\x01\n\x08ShortURL\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08shortUrl\x18\x02 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x03 \x01(\t\x12\x1e\n\x04user\x18\x04 \x01(\x0b\x32\x10.shorturlrn.User\x12\x13\n\x0b\x61\x63\x63\x65ssCount\x18\x05 \x01(\x05\x12,\n\naccessLogs\x18\x06 \x03(\x0b\x32\x18.shorturlrn.UrlAccessLog\"p\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x61\x64min\x18\x03 \x01(\x08\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\x08\x12)\n\x0eprofilePicture\x18\x05 \x01(\x0b\x32\x11.shorturlrn.Image\"G\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08mimeType\x18\x03 \x01(\t\x12\x12\n\nfotoBase64\x18\x04 \x01(\t\"\x89\x01\n\x0cUrlAccessLog\x12\n\n\x02id\x18\x01 \x01(\x03\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0f\n\x07\x62rowser\x18\x03 \x01(\t\x12\x14\n\x0c\x63lientDomain\x18\x04 \x01(\t\x12\n\n\x02os\x18\x05 \x01(\t\x12.\n\naccessTime\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x85\x01\n\x11ShortUrlResponses\x12\x13\n\x0boriginalUrl\x18\x01 \x01(\t\x12\x10\n\x08shortUrl\x18\x02 \x01(\t\x12-\n\tcreatedAt\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1a\n\x12previewImageBase64\x18\x04 \x01(\t2\xac\x01\n\nShortUrlRn\x12K\n\rgetUrlsByUser\x12\x18.shorturlrn.UserRequests\x1a .shorturlrn.UserUrlListResponses\x12Q\n\x11\x63reateShortUrlAPI\x12\x1d.shorturlrn.CreateUrlRequests\x1a\x1d.shorturlrn.ShortUrlResponsesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ShortUrlRn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUESTS']._serialized_start=65
  _globals['_USERREQUESTS']._serialized_end=97
  _globals['_USERURLLISTRESPONSES']._serialized_start=99
  _globals['_USERURLLISTRESPONSES']._serialized_end=157
  _globals['_CREATEURLREQUESTS']._serialized_start=159
  _globals['_CREATEURLREQUESTS']._serialized_end=217
  _globals['_SHORTURL']._serialized_start=220
  _globals['_SHORTURL']._serialized_end=380
  _globals['_USER']._serialized_start=382
  _globals['_USER']._serialized_end=494
  _globals['_IMAGE']._serialized_start=496
  _globals['_IMAGE']._serialized_end=567
  _globals['_URLACCESSLOG']._serialized_start=570
  _globals['_URLACCESSLOG']._serialized_end=707
  _globals['_SHORTURLRESPONSES']._serialized_start=710
  _globals['_SHORTURLRESPONSES']._serialized_end=843
  _globals['_SHORTURLRN']._serialized_start=846
  _globals['_SHORTURLRN']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
