# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ShortUrlRn_pb2 as ShortUrlRn__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ShortUrlRn_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShortUrlRnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getUrlsByUser = channel.unary_unary(
                '/shorturlrn.ShortUrlRn/getUrlsByUser',
                request_serializer=ShortUrlRn__pb2.UserRequests.SerializeToString,
                response_deserializer=ShortUrlRn__pb2.UserUrlListResponses.FromString,
                _registered_method=True)
        self.createShortUrlAPI = channel.unary_unary(
                '/shorturlrn.ShortUrlRn/createShortUrlAPI',
                request_serializer=ShortUrlRn__pb2.CreateUrlRequests.SerializeToString,
                response_deserializer=ShortUrlRn__pb2.ShortUrlResponses.FromString,
                _registered_method=True)


class ShortUrlRnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getUrlsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createShortUrlAPI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShortUrlRnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getUrlsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.getUrlsByUser,
                    request_deserializer=ShortUrlRn__pb2.UserRequests.FromString,
                    response_serializer=ShortUrlRn__pb2.UserUrlListResponses.SerializeToString,
            ),
            'createShortUrlAPI': grpc.unary_unary_rpc_method_handler(
                    servicer.createShortUrlAPI,
                    request_deserializer=ShortUrlRn__pb2.CreateUrlRequests.FromString,
                    response_serializer=ShortUrlRn__pb2.ShortUrlResponses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shorturlrn.ShortUrlRn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shorturlrn.ShortUrlRn', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShortUrlRn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getUrlsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shorturlrn.ShortUrlRn/getUrlsByUser',
            ShortUrlRn__pb2.UserRequests.SerializeToString,
            ShortUrlRn__pb2.UserUrlListResponses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createShortUrlAPI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shorturlrn.ShortUrlRn/createShortUrlAPI',
            ShortUrlRn__pb2.CreateUrlRequests.SerializeToString,
            ShortUrlRn__pb2.ShortUrlResponses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
